apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pr-vigilante.fullname" . }}
  labels:
    {{- include "pr-vigilante.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "pr-vigilante.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "pr-vigilante.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          args:
            {{- if .Values.extraArgs }}
              {{- include "pr-vigilante.args" . | nindent 12 }}
            {{- end }}
          env:
            {{- if .Values.extraEnv }}
              {{- include "pr-vigilante.env" . | nindent 12 }}
            {{- end }}
          volumeMounts:
            {{- if .Values.persistence.enabled }}
            - name: "{{ include "pr-vigilante.name" . }}"
              mountPath: {{ .Values.persistence.cacheDirPath }}
            {{- end }}
      volumes:
        {{- if .Values.persistence.enabled }}
        - name: "{{ include "pr-vigilante.name" . }}"
          persistentVolumeClaim:
            claimName: "{{ include "pr-vigilante.name" . }}"
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
